icmo/apps/billing/urls.py
from django.conf.urls import url, include

from . import views
import billing.providers.paypal_rest.views

urlpatterns = [
    url(r'^contracts/(?P<slug>[\w-]+)/$', views.ContractView.as_view(), name='contract_view'),
    url(r'^subscription/canceled/$',
        billing.providers.paypal_rest.views.SubscriptionCanceledView.as_view(),
        name='subscription_canceled'),
    url(r'^code/check/', views.AjaxCheckCouponView.as_view(), name='ajax_check_code'),
    url(r'^subscription/payment_summary/', views.AjaxUpdatePaymentSummaryView.as_view(),
        name='ajax_update_payment_summary'),

    url(r'^providers/paypal/', include('billing.providers.paypal_rest.urls', namespace='paypal')),
]

icmo/apps/leads/urls.py
from django.conf.urls import url
from leads import views
urlpatterns = [
    url(r'^program_mix/$', views.ProgramMixView.as_view(), name='program_mix'),
]

icmo/apps/pardot/urls.py
from django.conf.urls import patterns, url
from pardot import views
urlpatterns = [
    url(r'campaigns/([0-9]+)/test.html', views.pardot_test),
]

icmo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.templatetags.static import static
from django.views.generic import RedirectView

from core import views as core_views
from core.views import KendoProxyView

admin.autodiscover()

prefixed_urls = [
    url(r'^revenue/', include('revenues.urls')),
    url(r'^programs/', include('leads.urls')),
    url(r'^budgets/', include('budgets.urls')),
    url(r'^performance/', include('performance.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^dashboards/', include('dashboards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^integrations/', include('integrations.urls')),
    url(r'^task_boards/', include('task_boards.urls')),
    url(r'^reports/', include('reports.urls')),
]

urlpatterns = [
    url(r'^favicon\.ico$',
        RedirectView.as_view(url=static('img/favicon/favicon.ico'), permanent=True),
        name='favicon'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^django-rq/', include('django_rq.urls')),  # django-rq

    url(r'^api/', include('icmo.api_urls')),  # Rest Framework

    # Safari and older browses cannot save pdf and excel directly from the browser
    # They need this endpoint
    url(r'^k/save/$', KendoProxyView.as_view()),

    # Stripe and Paypal URLs
    # url(r'^payments/signup/paypalipn/', include('paypal.standard.ipn.urls')),
    # url(r'^payments/postbackz', paypal_standard_ipn_views.ipn, name="paypal-ipn"),

    url(r'^', include(prefixed_urls)),
    url(r'^company/(?P<company_slug>[\w-]+)/', include(prefixed_urls)),
    url(r'^company/(?P<company_slug>[\w-]+)/(?P<plan_slug>[\w-]+)/', include(prefixed_urls)),

    # Permission denied views
    url(r'^permission_denied/$', core_views.PermissionDeniedView.as_view(),
        name='permission_denied'),
    url(r'^no_published_plan/$', core_views.NoPublishedPlanView.as_view(),
        name='no_published_plan'),

    # Redirects that set the active Company and RevenuePlan
    url(r'^$', core_views.LoginRedirectView.as_view(), name='start_redirect'),
    url(r'^switch_plan/$', core_views.SwitchPlanRedirectView.as_view(), name='switch_plan'),
    url(r'^switch_company/$', core_views.SwitchCompanyRedirectView.as_view(),
        name='switch_company'),

    url(r'^account/', include('icmo_users.urls')),
    url(r'^pardot/', include('pardot.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),

    # url(r'^salesforce/', include('salesforce_icmo.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

icmo/apps/accounts/models.py
from django.db import models

# Create your models here.

icmo/apps/billing/providers/stripe/models.py
from django.db import models

from billing.helpers import apply_to_price


class StripeSubscriptionPlanRegistry(models.Model):
    icmo_plan = models.ForeignKey('billing.SubscriptionPlan')
    stripe_plan_id = models.CharField(max_length=255)

    # These aren't captureable in stripe so we record them here separately
    setup_fee_name = models.CharField(max_length=100, blank=True)
    setup_fee_amount = models.PositiveIntegerField(default=0)


class StripeSubscriptionRegistry(models.Model):
    icmo_subscription = models.ForeignKey('billing.Subscription')
    stripe_subscription_id = models.CharField(max_length=255)
    stripe_customer_id = models.CharField(max_length=255)
    card_last_4 = models.CharField(max_length=4, blank=True)
    card_kind = models.CharField(max_length=50, blank=True)
    card_exp_month = models.PositiveIntegerField(blank=True, null=True)
    card_exp_year = models.PositiveIntegerField(blank=True, null=True)


class StripeCouponRegistry(models.Model):
    """
    ICMO coupons affecting both setup fee and recurring fee must be split into two stripe coupons
    This model tracks them.
    """
    icmo_coupon = models.ForeignKey('billing.Coupon')
    stripe_coupon_id = models.CharField(max_length=255, blank=True)

    # These aren't captureable in stripe so we record them here separately
    setup_fee_amount_off = models.DecimalField(max_digits=7, decimal_places=2, blank=True,
                                               null=True)
    setup_fee_percent_off = models.PositiveIntegerField(blank=True, null=True)

    def get_discounted_setup_fee(self, setup_fee_amount):
        if self.setup_fee_amount_off:
            return int(apply_to_price('amount_off', self.setup_fee_amount_off, setup_fee_amount))
        elif self.setup_fee_percent_off:
            return int(apply_to_price('percent_off', self.setup_fee_percent_off, setup_fee_amount))
        return setup_fee_amount

icmo/apps/dashboards/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from core.models import IcmoModel


class Dashboard(IcmoModel):
    class Meta:
        unique_together = ('company', 'slug')
    slug = AutoSlugField(populate_from=('company', 'name'))
    company = models.ForeignKey('companies.Company', blank=True, null=True)
    user = models.ForeignKey('icmo_users.IcmoUser', blank=True, null=True)
    name = models.CharField(max_length=255)

icmo/apps/demos/models.py
from dirtyfields import DirtyFieldsMixin
from django.db import models
from django_extensions.db.models import TimeStampedModel

from demos.plan_templates import FourMRevenuePlanTemplate, TenMRevenuePlanTemplate
from .helpers import create_demo_company
from .tasks import task_create_demo_revenue_plan


class REVENUE_PLAN_TEMPLATES:
    TenM = '10M'
    FourM = '4M'


REVENUE_PLAN_TEMPLATE_MAP = {
    REVENUE_PLAN_TEMPLATES.TenM: TenMRevenuePlanTemplate,
    REVENUE_PLAN_TEMPLATES.FourM: FourMRevenuePlanTemplate
}

REVENUE_PLAN_TEMPLATE_CHOICES = (
    (REVENUE_PLAN_TEMPLATES.TenM, '$10 Million Company'),
    (REVENUE_PLAN_TEMPLATES.FourM, '$4 Million Company'),
)


class DemoAccount(DirtyFieldsMixin, TimeStampedModel):
    company_name = models.CharField(max_length=255)
    email = models.EmailField(
        help_text='This should be an email that does not yet exist on the system.')
    password = models.CharField(max_length=255, default='icmo')
    template = models.CharField(max_length=255, choices=REVENUE_PLAN_TEMPLATE_CHOICES,
                                default=REVENUE_PLAN_TEMPLATES.TenM)
    company = models.ForeignKey('companies.Company', editable=False)

    def save(self, *args, **kwargs):
        created = not self.pk
        if created:
            self.company = create_demo_company(self.company_name, self.email, self.password)
        super(DemoAccount, self).save(*args, **kwargs)
        if created:
            task_create_demo_revenue_plan.delay(self.company.id,
                                                REVENUE_PLAN_TEMPLATE_MAP[self.template])

icmo/apps/icmo_users/models.py
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.core.mail import EmailMultiAlternatives, send_mail
from django.db import models
from django.template import Context
from django.template.loader import get_template
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import ShortUUIDField
from django_extensions.db.fields.json import JSONField
from django_extensions.db.models import TimeStampedModel
from localflavor.us.models import PhoneNumberField
from timezone_field import TimeZoneField

from companies.models import Company
from core.models import ActiveManager


class IcmoUserManager(BaseUserManager):
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves an IcmoUser with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_superuser=is_superuser,
                          last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class IcmoUser(AbstractBaseUser, PermissionsMixin):
    """
        The basic user model for this application. he main difference between
        this user model and and the stock django one is that there is no
        username and identity is established by email which is, of course,
        a required field. 
    """
    first_name = models.CharField(_('First Name'), max_length=30)
    last_name = models.CharField(_('Last Name'), max_length=30)
    email = models.EmailField(_('Email'), unique=True)
    phone_number = PhoneNumberField(blank=True)
    title = models.CharField(help_text='Title Override', max_length=255, blank=True)
    is_staff = models.BooleanField(_('Staff status'), default=False,
                                   help_text=_(
                                       'Designates whether the user can log into this admin '
                                       'site.'))
    is_admin = models.BooleanField(_('Admin status'), default=False,
                                   help_text=_('Designates whether the user is an admin'))
    is_beta = models.BooleanField(_('Sees Beta Features'), default=False,
                                  help_text="Designates whether this user can see beta features")
    is_active = models.BooleanField(_('Active'), default=True,
                                    help_text=_(
                                        'Designates whether this user should be treated as '
                                        'active. Unselect this instead of deleting billing.'))
    date_joined = models.DateTimeField(_('Date joined'), auto_now_add=True)
    last_revenue_plan = models.ForeignKey('revenues.RevenuePlan', editable=False, blank=True,
                                          null=True, on_delete=models.SET_NULL)
    activation_token = ShortUUIDField(unique=True)

    company = models.CharField(help_text='Company Name Override', max_length=255, blank=True)
    timezone = TimeZoneField(default='America/Los_Angeles')

    companies = models.ManyToManyField('companies.Company', through='companies.CompanyUser',
                                       through_fields=('user', 'company'))

    objects = IcmoUserManager()
    active = ActiveManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def deactivate(self):
        self.is_active = False
        return self.save()

    @cached_property
    def companies_slugs(self):
        return [x.slug for x in self.companies.all()]

    @property
    def is_account_owner(self):
        return hasattr(self, 'billingaccount')

    @property
    def full_name(self):
        return self.get_full_name()

    @property
    def initials(self):
        return "%s%s" % (self.first_name[0].upper(), self.last_name[0].upper())

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

    @cached_property
    def owned_companies(self):
        return Company.objects.filter(
            id__in=self.permissions.filter(owner=True).values('company_id'))

    @cached_property
    def shared_companies(self):
        return Company.objects.filter(
            id__in=self.permissions.filter(owner=False).values('company_id'))

    @cached_property
    def can_create_company(self):
        if not hasattr(self, 'billingaccount') or not self.billingaccount:
            return False
        if self.owned_companies >= self.billingaccount.limit_max_companies:
            return False
        return True

    @cached_property
    def employer_name(self):
        if self.company:
            return self.company
        return self.owned_companies.first().name

    @classmethod
    def get_or_create_user(cls, email, first_name, last_name, password):
        try:
            user = cls.objects.get(email=email)
        except cls.DoesNotExist:
            user = cls.objects.create(
                first_name=first_name, last_name=last_name,
                email=email, password=password
            )
            user.set_password(password)
            user.save()
        return user


class Referral(models.Model):
    """ Keeps track of when someone refers us to their friends. Automatically
        sends an email at creation"""
    referrer = models.ForeignKey(IcmoUser, related_name='referrals')
    email = models.EmailField(_('email address'), unique=False)
    message = models.TextField(blank=True, null=True)
    date_sent = models.DateTimeField(_('date sent'), default=None,
                                     null=True)

    def send_referral(self):
        # todo revise this
        subject = get_template('icmo_users/email/referral_subject.txt')
        subject_content = subject.render(Context({'user': self.referrer}))
        subject_content = subject_content.replace('\n', '')

        plaintext = get_template('icmo_users/email/referral_email.txt')
        plaintext_content = plaintext.render(
            Context({'message': self.message,
                     'user': self.referrer,
                     'dest': settings.REFERRAL_LANDING_PAGE})
        )

        htmlish = get_template('icmo_users/email/referral_email.html')
        htmlish_content = plaintext.render(
            Context({'message': self.message,
                     'user': self.referrer,
                     'dest': settings.REFERRAL_LANDING_PAGE})
        )

        msg = EmailMultiAlternatives(subject_content, plaintext_content,
                                     self.referrer.email,
                                     [self.email])
        msg.attach_alternative(htmlish_content, "text/html")
        try:
            m = msg.send()
            if int(m) > 0:
                self.date_sent = timezone.now()
                if self.pk:
                    self.save()
        except:
            pass

    def save(self, *args, **kwargs):
        if not self.pk:
            self.send()
        super(self, Referral).save(*args, **kwargs)


class Suggestion(models.Model):
    """ Keeps track of when someone sends us a suggestion. Automatically
        sends an email at creation"""
    user = models.ForeignKey(IcmoUser, related_name='suggestions')
    message = models.TextField(blank=True, null=True)
    date_sent = models.DateTimeField(_('date sent'), default=None,
                                     null=True)

    def send(self):
        subject = 'iCMO suggestion from ' + self.user.email
        message = self.message
        msg = EmailMultiAlternatives(subject, message,
                                     self.user.email,
                                     [settings.SUPPORT_EMAIL])
        msg.send()
        self.date_sent = timezone.now()
        if self.pk:
            self.save()
        return True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.send()
        super(Suggestion, self).save(*args, **kwargs)


class SignupLead(TimeStampedModel):
    first_name = models.CharField(max_length=30, blank=True, editable=False)
    last_name = models.CharField(max_length=30, blank=True, editable=False)
    email = models.EmailField(unique=True, editable=False)
    phone_number = PhoneNumberField(blank=True, editable=False)
    title = models.CharField(max_length=255, blank=True, editable=False)
    company_name = models.CharField(max_length=255, blank=True, editable=False)
    fields = JSONField(editable=False)

icmo/apps/pardot/models.py
from django.db import models

# Create your models here.

icmo/apps/reports/models.py
from django.db import models

# Create your models here.

icmo/templates/icmo_users/activate_invited_user.html
{% extends 'base_standalone.html' %}
{% load staticfiles %}
{% block title %}Activate your Account{% endblock %}
{% block page_js %}
    {{ block.super }}
    <script type="text/javascript">
        $(function () {
            $('#activateInvitedUserForm').formValidation({
                framework: 'bootstrap',
                icon: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                excluded: ':disabled'
            });
        });
    </script>
{% endblock %}
{% block content %}
    {% if invited_user %}
        {% if invitation %}
            <h2>Welcome! Activate Your Account</h2>
            <p>
                You have received an invitation to collaborate on
                <b>{{ invitation.company.name }}</b> from
                <b>{{ invitation.inviting_user.full_name }}</b>. Fill out the form below to
                activate your account
                and
                get started with intelligentRevenue.
            </p>
            <hr>
            <form id='activateInvitedUserForm' class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name"
                           class="control-label col-lg-2 requiredField">
                        First Name<span class="asteriskField">*</span>
                    </label>

                    <div class="controls col-lg-8">
                        <input class="form-control"
                               id="id_first_name" name="first_name"
                               required="required"
                               type="text"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_last_name"
                           class="control-label col-lg-2 requiredField">
                        Last Name<span class="asteriskField">*</span>
                    </label>

                    <div class="controls col-lg-8">
                        <input class="form-control"
                               id="id_last_name" name="last_name"
                               required="required"
                               type="text"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password"
                           class="control-label col-lg-2 requiredField">
                        Password<span class="asteriskField">*</span>
                    </label>

                    <div class="controls col-lg-8">
                        <input class="form-control"
                               id="id_password" name="password"
                               required="required"
                               type="password"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password2"
                           class="control-label col-lg-2 requiredField">
                        Password Confirmation<span class="asteriskField">*</span>
                    </label>

                    <div class="controls col-lg-8">
                        <input class="form-control"
                               data-fv-identical="true"
                               data-fv-identical-field="password"
                               data-fv-identical-message="Your passwords do not match, please check and try again."
                               id="id_password2" name="password_confirmation"
                               required="required"
                               type="password"/>
                    </div>
                </div>
                <input type="submit" class="btn btn-primary btn-bordered"
                       value="Activate My Account">
            </form>
        {% else %}
            <h2>Account Activated</h2>
            <p>Your account has been activated. <a href="{% url 'login' %}">You may now sign into
                intelligentRevenue</a>.
            </p>
        {% endif %}
    {% else %}
        <h2>Link Expired</h2>
        <p>
            This link is no longer valid. If you need to change your password
            please do so via the <a
                href="{% url 'password_reset' %}">password reset</a> function.
        </p>
    {% endif %}
{% endblock %}

icmo/templates/icmo_users/signup.html
{% extends 'base_standalone.html' %}
{% load staticfiles crispy_forms_tags %}
{% block title %}Sign Up{% endblock %}
{% block compressed_css %}
    {{ block.super }}
    <link href="{% static 'iCheck/skins/square/red.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'vendor/signature-pad/assets/jquery.signaturepad.css' %}"
          rel="stylesheet">
    <link href="{% static 'css/stripe_form.css' %}" rel="stylesheet">
{% endblock %}
{% block compressed_js %}
    {{ block.super }}
    <script src="{% static 'twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js' %}"
            type="text/javascript"></script>
    <!--[if lt IE 9]>
	<script src="{% static 'vendor/signature-pad/assets/flashcanvas.js' %}" type="text/javascript"></script>
	<![endif]-->
    <script src="{% static 'vendor/signature-pad/jquery.signaturepad.min.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'vendor/signature-pad/assets/json2.min.js' %}"
            type="text/javascript"></script>
    <script type="text/javascript"
            src="{% static 'jquery.payment/lib/jquery.payment.js' %}"></script>

    <script src="{% static 'phoenix/jquery.phoenix.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'iCheck/icheck.min.js' %}" type="text/javascript"></script>

    <script src="{% static 'js/signup_form.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/stripe_form.js' %}" type="text/javascript"></script>
{% endblock %}
{% block page_js %}
    {{ block.super }}
    <script>
        $(function () {
            SignupJS.init("#signupForm");
            StripeForm.init($signupForm, '{{ stripe_public_key }}');
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-red',
                radioClass: 'iradio_square-red',
                increaseArea: '20%' // optional
            });
        });
    </script>
{% endblock %}
{% block external_js %}
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
{% endblock %}
{% block body_content %}
    <div class="row inset">
        <div class="col-md-8 col-md-offset-2">
            <h1>
                <a href="/">
                    <img class='responsive'
                         height="25px"
                         src="{% static 'img/icmo-logo-443x50.png' %}"
                         alt="intelligentRevenue logo" title="intelligentRevenue"/>
                </a>
            </h1>

            <div class="box box-solid">
                <form id="signupForm" method="post" class="form-horizontal"
                      action="{% url 'signup_create_account' %}"
                      data-store-form-url="{% url 'ajax_signup_store_form' %}"
                      data-summary-url="{% url 'billing:ajax_update_payment_summary' %}">

                    <input type="hidden" name="_last_tab" id="_last_tab">

                    <div class="alert alert-success" id='welcome_back_alert' role="alert"
                         style="display:none">
                        Welcome back! Pick up where you left off.
                        <button type="button" class="close" data-dismiss="alert"
                                aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="box-header with-border no-padding">
                        <ul class="nav">
                            <li class="active">
                                <a href="#welcome-tab" data-toggle="tab">Welcome</a>
                            </li>
                            <li>
                                <a href="#solution-tab" data-toggle="tab">Solution</a>
                            </li>
                            <li>
                                <a href="#contact-tab" data-toggle="tab">Contact</a>
                            </li>
                            <li>
                                <a href="#company-tab" data-toggle="tab">Company</a>
                            </li>
                            <li>
                                <a href="#order-tab" data-toggle="tab">Order</a>
                            </li>
                            <li>
                                <a href="#payment-tab" data-toggle="tab">Payment</a>
                            </li>
                            <li>
                                <a href="#">Finish</a>
                            </li>
                        </ul>
                    </div>
                    <div class="box-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="welcome-tab">
                                <h3>Welcome to the signup wizard.</h3>
                                You will be guided through a series of steps to create your
                                company account. The process will take five minutes to complete.
                            </div>
                            <div class="tab-pane" id="solution-tab">
                                <h3>Please select a solution for your company:</h3>
                                {% include 'icmo_users/includes/plan_chooser.html' %}
                                {% crispy subscription_plan_form %}
                            </div>
                            <div class="tab-pane" id="contact-tab">
                                <h3>Please create your user information:</h3>
                                {% crispy contact_form %}
                            </div>
                            <div class="tab-pane" id="company-tab">
                                <h3>Please create your company account:</h3>

                                {% crispy company_form %}
                            </div>
                            <div class="tab-pane" id="order-tab">
                                <h3>Please Review & Sign this Order Form
                                    <small><br>You will receive a countersigned copy of this order
                                        form as a pdf by email.
                                    </small>
                                </h3>

                                <div class='well'>
                                    <h4 class="text-bold">intelligentRevenue Order Form</h4>
                                    <hr>
                                    {% include 'billing/includes/payment_summary.html' with loading_bar=True %}
                                    <hr>
                                    {% include contract_template_name %}
                                    <hr>
                                    {% crispy contract_form %}
                                </div>
                            </div>
                            <div class="tab-pane" id="payment-tab">
                                <h3>Please review your order and select a payment method.</h3>

                                <div class="row">
                                    <div class="col-sm-8 col-sm-push-2">
                                        {% include 'billing/includes/payment_summary.html' with loading_bar=True coupon_form=None %}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-8 col-sm-push-2">
                                        {% include 'billing/stripe_form.html' %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-8 col-sm-push-2">
                                        {% include 'billing/paypal_form.html' %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="button" class="btn btn-primary btn-bordered wizard-prev">
                            Previous
                        </button>
                        <button type="button"
                                class="btn btn-primary btn-bordered wizard-next pull-right">
                            Next
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}