icmo/apps/billing/urls.py
from django.conf.urls import url, include

from . import views
import billing.providers.paypal_rest.views

urlpatterns = [
    url(r'^contracts/(?P<slug>[\w-]+)/$', views.ContractView.as_view(), name='contract_view'),
    url(r'^subscription/canceled/$',
        billing.providers.paypal_rest.views.SubscriptionCanceledView.as_view(),
        name='subscription_canceled'),
    url(r'^code/check/', views.AjaxCheckCouponView.as_view(), name='ajax_check_code'),
    url(r'^subscription/payment_summary/', views.AjaxUpdatePaymentSummaryView.as_view(),
        name='ajax_update_payment_summary'),

    url(r'^providers/paypal/', include('billing.providers.paypal_rest.urls', namespace='paypal')),
]

icmo/apps/leads/urls.py
from django.conf.urls import url
from leads import views
urlpatterns = [
    url(r'^program_mix/$', views.ProgramMixView.as_view(), name='program_mix'),
]

icmo/apps/pardot/urls.py
from django.conf.urls import patterns, url
from pardot import views
urlpatterns = [
    url(r'campaigns/([0-9]+)/test.html', views.pardot_test),
]

icmo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.templatetags.static import static
from django.views.generic import RedirectView

from core import views as core_views
from core.views import KendoProxyView

admin.autodiscover()

prefixed_urls = [
    url(r'^revenue/', include('revenues.urls')),
    url(r'^programs/', include('leads.urls')),
    url(r'^budgets/', include('budgets.urls')),
    url(r'^performance/', include('performance.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^dashboards/', include('dashboards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^integrations/', include('integrations.urls')),
    url(r'^task_boards/', include('task_boards.urls')),
    url(r'^reports/', include('reports.urls')),
]

urlpatterns = [
    url(r'^favicon\.ico$',
        RedirectView.as_view(url=static('img/favicon/favicon.ico'), permanent=True),
        name='favicon'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^django-rq/', include('django_rq.urls')),  # django-rq

    url(r'^api/', include('icmo.api_urls')),  # Rest Framework

    # Safari and older browses cannot save pdf and excel directly from the browser
    # They need this endpoint
    url(r'^k/save/$', KendoProxyView.as_view()),

    # Stripe and Paypal URLs
    # url(r'^payments/signup/paypalipn/', include('paypal.standard.ipn.urls')),
    # url(r'^payments/postbackz', paypal_standard_ipn_views.ipn, name="paypal-ipn"),

    url(r'^', include(prefixed_urls)),
    url(r'^company/(?P<company_slug>[\w-]+)/', include(prefixed_urls)),
    url(r'^company/(?P<company_slug>[\w-]+)/(?P<plan_slug>[\w-]+)/', include(prefixed_urls)),

    # Permission denied views
    url(r'^permission_denied/$', core_views.PermissionDeniedView.as_view(),
        name='permission_denied'),
    url(r'^no_published_plan/$', core_views.NoPublishedPlanView.as_view(),
        name='no_published_plan'),

    # Redirects that set the active Company and RevenuePlan
    url(r'^$', core_views.LoginRedirectView.as_view(), name='start_redirect'),
    url(r'^switch_plan/$', core_views.SwitchPlanRedirectView.as_view(), name='switch_plan'),
    url(r'^switch_company/$', core_views.SwitchCompanyRedirectView.as_view(),
        name='switch_company'),

    url(r'^account/', include('icmo_users.urls')),
    url(r'^pardot/', include('pardot.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),

    # url(r'^salesforce/', include('salesforce_icmo.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

icmo/apps/accounts/models.py
from django.db import models

# Create your models here.

icmo/apps/billing/providers/stripe/models.py
from django.db import models

from billing.helpers import apply_to_price


class StripeSubscriptionPlanRegistry(models.Model):
    icmo_plan = models.ForeignKey('billing.SubscriptionPlan')
    stripe_plan_id = models.CharField(max_length=255)

    # These aren't captureable in stripe so we record them here separately
    setup_fee_name = models.CharField(max_length=100, blank=True)
    setup_fee_amount = models.PositiveIntegerField(default=0)


class StripeSubscriptionRegistry(models.Model):
    icmo_subscription = models.ForeignKey('billing.Subscription')
    stripe_subscription_id = models.CharField(max_length=255)
    stripe_customer_id = models.CharField(max_length=255)
    card_last_4 = models.CharField(max_length=4, blank=True)
    card_kind = models.CharField(max_length=50, blank=True)
    card_exp_month = models.PositiveIntegerField(blank=True, null=True)
    card_exp_year = models.PositiveIntegerField(blank=True, null=True)


class StripeCouponRegistry(models.Model):
    """
    ICMO coupons affecting both setup fee and recurring fee must be split into two stripe coupons
    This model tracks them.
    """
    icmo_coupon = models.ForeignKey('billing.Coupon')
    stripe_coupon_id = models.CharField(max_length=255, blank=True)

    # These aren't captureable in stripe so we record them here separately
    setup_fee_amount_off = models.DecimalField(max_digits=7, decimal_places=2, blank=True,
                                               null=True)
    setup_fee_percent_off = models.PositiveIntegerField(blank=True, null=True)

    def get_discounted_setup_fee(self, setup_fee_amount):
        if self.setup_fee_amount_off:
            return int(apply_to_price('amount_off', self.setup_fee_amount_off, setup_fee_amount))
        elif self.setup_fee_percent_off:
            return int(apply_to_price('percent_off', self.setup_fee_percent_off, setup_fee_amount))
        return setup_fee_amount

icmo/apps/companies/models.py
from cloudinary.models import CloudinaryField
from django.apps import apps
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.dates import MONTHS
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

from companies.notifications import send_share_notification_email, \
    send_invited_user_activation_email
from core.helpers import get_fiscal_year_quarters, get_fiscal_year_months, \
    get_fiscal_quarter_by_month_name, MONTHS_FULL, MONTHS_3
from core.models import IcmoModel, SORTED_STATE_AND_PROVINCE, COUNTRY_CHOICES, BLANK_CHOICE
from revenues.models import RevenuePlan


class NoLivePlanException(Exception):
    pass


class AppPermissions(object):
    NONE = 'none'
    VIEW = 'view'
    CHANGE = 'change'

    choices = (
        (NONE, 'None'),
        (VIEW, 'View'),
        (CHANGE, 'Change'),
    )


class SharePermissions(object):
    NONE = 'none'
    MODERATED = 'moderated'
    UNMODERATED = 'unmoderated'

    choices = (
        (NONE, 'None'),
        (NONE, 'View'),
        (NONE, 'Change'),
    )


class Company(IcmoModel):
    class Meta:
        verbose_name_plural = "Companies"
        permissions = (
            ('view_company', 'View company'),
        )
        unique_together = (('account', 'name'), ('account', 'slug'))

    account = models.ForeignKey('billing.BillingAccount', related_name='companies')
    name = models.CharField(_('Company Name'), max_length=150)
    slug = AutoSlugField(populate_from='name')
    website = models.URLField(max_length=150, blank=True)
    address1 = models.CharField(_('Address 1'), max_length=255)
    address2 = models.CharField(_('Address 2'), max_length=255, blank=True)
    city = models.CharField(max_length=75)
    state = models.CharField(max_length=2,
                             choices=BLANK_CHOICE + SORTED_STATE_AND_PROVINCE)
    zip = models.CharField(max_length=12)
    country = models.CharField(max_length=3, choices=BLANK_CHOICE + COUNTRY_CHOICES,
                               default='US')
    logo = CloudinaryField(blank=True, null=True)
    fiscal_year_start = models.PositiveSmallIntegerField(choices=MONTHS.items(), default=1)

    @cached_property
    def segments(self):
        return self.segment_set.filter(is_active=True)

    @property
    def revenue_plans(self):
        return self.revenueplan_set.filter(is_active=True)

    @property
    def published_revenue_plan(self):
        try:
            return self.revenue_plans.get(plan_type='published')
        except ObjectDoesNotExist:
            return None

    @cached_property
    def has_active_subscription(self):
        return self.account.has_active_subscription()

    @cached_property
    def active_plans(self):
        return self.revenue_plans.filter(is_active=True)

    @property
    def fiscal_year_start_full_name(self):
        return MONTHS_FULL[self.fiscal_year_start - 1]

    @property
    def fiscal_quarters(self):
        return get_fiscal_year_quarters(self.fiscal_year_start)

    @property
    def fiscal_quarters_by_name(self):
        return get_fiscal_year_quarters(self.fiscal_year_start, month_type='name')

    def get_fiscal_quarter_by_month_name(self, month_name):
        return get_fiscal_quarter_by_month_name(self.fiscal_year_start, month_name)

    def get_current_quarter(self):
        return self.get_fiscal_quarter_by_month_name(MONTHS_3[timezone.now().month - 1])

    @property
    def fiscal_months(self):
        return get_fiscal_year_months(self.fiscal_year_start)

    @property
    def fiscal_months_by_name(self):
        return get_fiscal_year_months(self.fiscal_year_start, month_type='name')

    def assign_owner(self, user, title=None):
        if self.users.filter(owner=True).count() != 0:
            raise ValueError("This company already has an owner.")
        if not title:
            title = ""
        return CompanyUser.objects.create(
            company=self,
            user=user,
            group=CompanyUserGroup.objects.get(company=self, name='Admin', editable=False),
            owner=True,
            title=title
        )

    def assign_user(self, user, group, title=None):
        if not title:
            title = ""
        try:
            group = CompanyUserGroup.objects.get(company=self, name=group)
        except CompanyUserGroup.DoesNotExist:
            raise ValueError("Group `%s` not found" % group)
        company_user, created = CompanyUser.objects.get_or_create(defaults=dict(group=group),
                                                                  company=self, user=user,
                                                                  title=title)
        return company_user

    def create_default_plan(self):
        from demos.tasks import task_create_sample_revenue_plan
        task_create_sample_revenue_plan.delay(self.id)

    @cached_property
    def logo_thumbnail(self):
        if self.logo:
            return self.logo.build_url(height=60, crop='fit')
        return None

    @cached_property
    def logo_large(self):
        if self.logo:
            return self.logo.build_url(height=100, crop='fit')
        return None

    @cached_property
    def url(self):
        return self.get_absolute_url()

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('companies_list', kwargs=dict(company_slug=self.slug))

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        created = not self.pk
        super(Company, self).save(*args, **kwargs)
        if created:
            # Every new company instance gets a default revenue plan
            # Note that this is queued, and may take a couple minutes
            self.create_default_plan()
            # and a set of default user groups
            CompanyUserGroup.create_default_groups(self)


class CompanyUserGroup(IcmoModel):
    icmo_parent_levels = ('company',)

    class Meta:
        unique_together = ('company', 'name')

    slug = AutoSlugField(populate_from='name')
    name = models.CharField(max_length=255)
    company = models.ForeignKey('Company')
    editable = models.BooleanField(default=True,
                                   help_text="Some default plans should never be deleted or "
                                             "edited by the user")
    revenue_plans = models.CharField(max_length=50, default=AppPermissions.NONE,
                                     choices=AppPermissions.choices)
    program_mix = models.CharField(max_length=50, default=AppPermissions.NONE,
                                   choices=AppPermissions.choices)
    budgets = models.CharField(max_length=50, default=AppPermissions.NONE,
                               choices=AppPermissions.choices)
    performance = models.CharField(max_length=50, default=AppPermissions.NONE,
                                   choices=AppPermissions.choices)
    resources = models.CharField(max_length=50, default=AppPermissions.NONE,
                                 choices=AppPermissions.choices)
    timeline = models.CharField(max_length=50, default=AppPermissions.NONE,
                                choices=AppPermissions.choices)
    task_boards = models.CharField(max_length=50, default=AppPermissions.NONE,
                                   choices=AppPermissions.choices)
    dashboards = models.CharField(max_length=50, default=AppPermissions.NONE,
                                  choices=AppPermissions.choices)
    reports = models.CharField(max_length=50, default=AppPermissions.NONE,
                               choices=AppPermissions.choices)
    permissions = models.CharField(max_length=50, default=AppPermissions.NONE,
                                   choices=AppPermissions.choices)

    live_plan_only = models.BooleanField(default=True)
    permitted_segments_list = models.TextField(
        blank=True,
        help_text="Restrict this group to certain segments.  Each exact segment name should be "
                  "entered on a separate line.  Note, in the case that all of the segments a user "
                  "has access to are not found or are inactive, users from  this group will not "
                  "be able to access anything."
    )
    publish_plans = models.BooleanField(default=False)
    archive_plans = models.BooleanField(default=False)
    share = models.CharField(max_length=50, default=SharePermissions.NONE,
                             choices=SharePermissions.choices)
    moderate_shares = models.BooleanField(default=False)

    @staticmethod
    def create_default_groups(company):
        # Admin users can do everything, including manage revenue plans and moderate shares.
        CompanyUserGroup.objects.create(
            name='Admin',
            company=company,
            editable=False,
            revenue_plans=AppPermissions.CHANGE,
            program_mix=AppPermissions.CHANGE,
            budgets=AppPermissions.CHANGE,
            performance=AppPermissions.CHANGE,
            resources=AppPermissions.CHANGE,
            timeline=AppPermissions.CHANGE,
            task_boards=AppPermissions.CHANGE,
            dashboards=AppPermissions.CHANGE,
            reports=AppPermissions.CHANGE,
            permissions=AppPermissions.CHANGE,
            share=SharePermissions.UNMODERATED,
            live_plan_only=False,
            publish_plans=True,
            archive_plans=True,
            moderate_shares=True
        )
        # Planners can do everything with the live plan, but cannot create their own plans
        CompanyUserGroup.objects.create(
            name='Planner',
            company=company,
            revenue_plans=AppPermissions.VIEW,
            program_mix=AppPermissions.CHANGE,

icmo/apps/dashboards/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from core.models import IcmoModel


class Dashboard(IcmoModel):
    class Meta:
        unique_together = ('company', 'slug')
    slug = AutoSlugField(populate_from=('company', 'name'))
    company = models.ForeignKey('companies.Company', blank=True, null=True)
    user = models.ForeignKey('icmo_users.IcmoUser', blank=True, null=True)
    name = models.CharField(max_length=255)

icmo/apps/pardot/models.py
from django.db import models

# Create your models here.

icmo/apps/reports/models.py
from django.db import models

# Create your models here.

icmo/templates/companies/permissions.html
{% extends 'base_main.html' %}
{% load static from staticfiles %}
{% load i18n icmo_utils crispy_forms_tags %}
{% block title %}Permissions Management{% endblock %}
{% block page_title %}Permissions Management{% endblock %}
{% block compressed_js %}
    {{ block.super }}
    <script src="{% static 'js/permissions.js' %}" type="text/javascript"></script>
{% endblock %}
{% block page_js %}
    {{ block.super }}
    {% include 'misc_widgets/grid_row_tools.html' %}
    <script type="text/javascript">
        $(function () {
            {% for cu in company_users %}
                var groupGrid = ICMO.apps.permissions.groups.createGrid($('#grid-groups-{{cu.company.slug}}'));
                ICMO.apps.permissions.users.createGrid($('#grid-users-{{cu.company.slug}}'), groupGrid.dataSource);
            {% endfor %}
            ICMO.apps.permissions.initAddUserForm();
        });
    </script>
{% endblock %}
{% block content %}
    {% for cu in company_users %}
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ cu.company.name }}
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i
                                        class="fa fa-minus"></i></button>
                            </div>
                        </h3>
                    </div>
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#tab_{{ cu.company.slug }}_users" data-toggle="tab"
                                   aria-expanded="true">
                                    Users
                                </a>
                            </li>
                            <li>
                                <a href="#tab_{{ cu.company.slug }}_groups" data-toggle="tab"
                                   aria-expanded="false">
                                    Groups
                                </a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane tab-content segment-tab active"
                                 id="tab_{{ cu.company.slug }}_users">
                                <br>

                                <div class="box-tools grid-{{ cu.company.slug }}-users-tools">
                                    {% if cu.can_change_permissions %}
                                        <button class="btn btn-primary btn-bordered btn-sm grid-add-user"
                                                title="Add a new user">
                                            <i class="fa fa-plus"></i>&nbsp;
                                            User
                                        </button>
                                    {% endif %}
                                    <button class="btn btn-primary btn-sm grid-cancel"
                                            title="Cancel changes"
                                            disabled aria-disabled="true">
                                        <i class="fa fa-undo"></i>
                                    </button>
                                    <div class="btn-group" role="group" aria-label="...">
                                        <button class="btn btn-primary btn-sm grid-pdf"
                                                title="Export to PDF">
                                            <i class="fa fa-file-pdf-o"></i>
                                        </button>
                                        <button class="btn btn-primary btn-sm grid-excel"
                                                title="Export to Excel">
                                            <i class="fa fa-file-excel-o"></i>
                                        </button>
                                    </div>
                                </div>
                                <div id="grid-users-{{ cu.company.slug }}"
                                     class="grid-multiline-headers"
                                     data-tools="grid-{{ cu.company.slug }}-users-tools"
                                     data-api-url="
                                             {{ api_url }}{{ cu.company.slug }}/permissions/">
                                </div>
                            </div>
                            <div class="tab-pane tab-content segment-tab"
                                 id="tab_{{ cu.company.slug }}_groups">
                                <br>

                                <div class="box-tools grid-{{ cu.company.slug }}-groups-tools">
                                    {% if cu.can_change_permissions %}
                                        <!--
                                        <button class="btn btn-primary btn-bordered btn-sm grid-add"
                                                title="Add a new group">
                                            <i class="fa fa-plus"></i>&nbsp;
                                            Group
                                        </button>
                                        -->
                                    {% endif %}
                                    <button class="btn btn-primary btn-sm grid-cancel"
                                            title="Cancel changes"
                                            disabled aria-disabled="true">
                                        <i class="fa fa-undo"></i>
                                    </button>
                                    <div class="btn-group" role="group" aria-label="...">
                                        <button class="btn btn-primary btn-sm grid-pdf"
                                                title="Export to PDF">
                                            <i class="fa fa-file-pdf-o"></i>
                                        </button>
                                        <button class="btn btn-primary btn-sm grid-excel"
                                                title="Export to Excel">
                                            <i class="fa fa-file-excel-o"></i>
                                        </button>
                                    </div>

                                </div>
                                <div id="grid-groups-{{ cu.company.slug }}"
                                     class="grid-multiline-headers"
                                     data-tools="grid-{{ cu.company.slug }}-groups-tools"
                                     data-api-url="
                                             {{ api_url }}{{ cu.company.slug }}/groups/">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">No Manageable Companies</h3>
                    </div>
                    <div class="box-body">
                        You do not have permission to manage users on any of your companies. If you
                        think this is a mistake please contact the account owner.
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" data-api-url=""
         data-company-slug=""
         aria-labelledby="addUserModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="addUserModalLabel">Add User</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}

                        <div id="div_id_user" class="form-group">
                            <label for="id_user"
                                   class="control-label col-lg-2 requiredField">
                                Email<span class="asteriskField">*</span>
                            </label>

                            <div class="controls col-lg-8">
                                <input class="emailinput form-control"
                                       id="id_user" name="user"
                                       required="required"
                                       type="email"/>
                            </div>
                        </div>
                        <div id="div_id_group" class="form-group">
                            <label for="id_group"
                                   class="control-label col-lg-2 requiredField">
                                Group<span class="asteriskField">*</span>
                            </label>

                            <div class="controls col-lg-8">
                                <input required data-text-field="name" id="id_group" name="group"
                                       data-value-field="slug">
                            </div>
                        </div>
                        <div id="div_id_title" class="form-group">
                            <label for="id_title" class="control-label col-lg-2">
                                Title
                            </label>

                            <div class="controls col-lg-8">
                                <input class="textinput textInput form-control" id="id_title"
                                       maxlength="75" name="title" type="text"/>
                            </div>
                        </div>
                        <div id="div_id_permitted_segments_list" class="form-group">
                            <label for="id_permitted_segments_list"
                                   class="control-label col-lg-2">
                                Permitted segments list
                            </label>

                            <div class="controls col-lg-8">
                                <textarea class="textarea form-control"
                                          cols="40"
                                          id="id_permitted_segments_list"
                                          name="permitted_segments_list"
                                          rows="10"></textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-bordered"
                            data-dismiss="modal">Cancel
                    </button>
                    <button type="submit" class="btn btn-primary btn-bordered">Save</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}