icmo/apps/billing/urls.py
from django.conf.urls import url, include

from . import views
import billing.providers.paypal_rest.views

urlpatterns = [
    url(r'^contracts/(?P<slug>[\w-]+)/$', views.ContractView.as_view(), name='contract_view'),
    url(r'^subscription/canceled/$',
        billing.providers.paypal_rest.views.SubscriptionCanceledView.as_view(),
        name='subscription_canceled'),
    url(r'^code/check/', views.AjaxCheckCouponView.as_view(), name='ajax_check_code'),
    url(r'^subscription/payment_summary/', views.AjaxUpdatePaymentSummaryView.as_view(),
        name='ajax_update_payment_summary'),

    url(r'^providers/paypal/', include('billing.providers.paypal_rest.urls', namespace='paypal')),
]

icmo/apps/leads/urls.py
from django.conf.urls import url
from leads import views
urlpatterns = [
    url(r'^program_mix/$', views.ProgramMixView.as_view(), name='program_mix'),
]

icmo/apps/pardot/urls.py
from django.conf.urls import patterns, url
from pardot import views
urlpatterns = [
    url(r'campaigns/([0-9]+)/test.html', views.pardot_test),
]

icmo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.templatetags.static import static
from django.views.generic import RedirectView

from core import views as core_views
from core.views import KendoProxyView

admin.autodiscover()

prefixed_urls = [
    url(r'^revenue/', include('revenues.urls')),
    url(r'^programs/', include('leads.urls')),
    url(r'^budgets/', include('budgets.urls')),
    url(r'^performance/', include('performance.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^dashboards/', include('dashboards.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^integrations/', include('integrations.urls')),
    url(r'^task_boards/', include('task_boards.urls')),
    url(r'^reports/', include('reports.urls')),
]

urlpatterns = [
    url(r'^favicon\.ico$',
        RedirectView.as_view(url=static('img/favicon/favicon.ico'), permanent=True),
        name='favicon'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^django-rq/', include('django_rq.urls')),  # django-rq

    url(r'^api/', include('icmo.api_urls')),  # Rest Framework

    # Safari and older browses cannot save pdf and excel directly from the browser
    # They need this endpoint
    url(r'^k/save/$', KendoProxyView.as_view()),

    # Stripe and Paypal URLs
    # url(r'^payments/signup/paypalipn/', include('paypal.standard.ipn.urls')),
    # url(r'^payments/postbackz', paypal_standard_ipn_views.ipn, name="paypal-ipn"),

    url(r'^', include(prefixed_urls)),
    url(r'^company/(?P<company_slug>[\w-]+)/', include(prefixed_urls)),
    url(r'^company/(?P<company_slug>[\w-]+)/(?P<plan_slug>[\w-]+)/', include(prefixed_urls)),

    # Permission denied views
    url(r'^permission_denied/$', core_views.PermissionDeniedView.as_view(),
        name='permission_denied'),
    url(r'^no_published_plan/$', core_views.NoPublishedPlanView.as_view(),
        name='no_published_plan'),

    # Redirects that set the active Company and RevenuePlan
    url(r'^$', core_views.LoginRedirectView.as_view(), name='start_redirect'),
    url(r'^switch_plan/$', core_views.SwitchPlanRedirectView.as_view(), name='switch_plan'),
    url(r'^switch_company/$', core_views.SwitchCompanyRedirectView.as_view(),
        name='switch_company'),

    url(r'^account/', include('icmo_users.urls')),
    url(r'^pardot/', include('pardot.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),

    # url(r'^salesforce/', include('salesforce_icmo.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

icmo/apps/accounts/models.py
from django.db import models

# Create your models here.

icmo/apps/billing/models.py
from decimal import Decimal
import logging
from random import randint

import re
from dirtyfields import DirtyFieldsMixin
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django_extensions.db.fields import AutoSlugField
from django_extensions.db.models import TimeStampedModel
from django.utils.translation import ugettext_lazy as _

from django.conf import settings

from core.helpers import generate_pdf
from core.models import IcmoModel, ActiveManager, NoUpdatesModel
from .helpers import get_adjusted_fee, check_provider
from . import providers

logger = logging.getLogger(__name__)

PAYMENT_PROVIDER_STRIPE = 'stripe'
PAYMENT_PROVIDER_PAYPAL = 'paypal_rest'
PERMISSION_NONE = 0
PERMISSION_READ = 1
PERMISSION_WRITE = 2
PERMISSION_OWNER = 3
ACCESS_CHOICES = (
    (PERMISSION_READ, 'Read'), (PERMISSION_WRITE, 'Write'), (PERMISSION_NONE, 'None'))
SUBSCRIPTION_CHOICES = ((PAYMENT_PROVIDER_STRIPE, 'Stripe'), (PAYMENT_PROVIDER_PAYPAL, 'PayPal'))
CURRENCY_CHOICES = (('USD', 'USD'), ('CAD', 'CAD'))
INTERVAL_CHOICES = (('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year'))
SUBSCRIPTION_STATUS_CHOICES = (
    ('active', 'Active'),
    ('trialing', 'Trialing'),
    ('past_due', 'Past Due'),  # payment failed
    ('canceled', 'Canceled'),
    ('unpaid', 'Unpaid'),  # all payment attempts have failed
)

COUPON_TYPE_CHOICES = (
    ('forever', 'Forever'),
    ('once', 'Once'),
    ('repeating', 'Repeating'),
)


class ProviderBackedModel(DirtyFieldsMixin, TimeStampedModel):
    class Meta:
        abstract = True

    updateable_fields = ('is_active',)

    is_active = models.BooleanField(_('active'), default=False)
    is_live = models.BooleanField('live', default=False, editable=False)

    objects = models.Manager()
    active = ActiveManager()

    def _call_all_providers_action(self, action, *args, **kwargs):
        """
        Calls a method in a module for each provider specified in PROVIDERS
        The module is specified through Meta.provider_module
        :param args: The args if any to pass to the callable
        :rtype : dict:  dict of responses returned by the methods
        :param action: the method to call
        """
        for provider_name in settings.ICMO_BILLING_PROVIDERS:
            self._call_provider_action(provider_name, action, *args, **kwargs)
        return True

    def _call_provider_action(self, provider_name, action, *args, **kwargs):
        provider = getattr(providers, provider_name)
        klass = provider.get_handler(self.__class__.__name__)
        method = getattr(klass, action)
        method(self.pk, *args, **kwargs)

    def save(self, *args, **kwargs):
        dirty_fields = self.get_dirty_fields().keys()
        forbidden_changed_fields = set(dirty_fields) - set(self.updateable_fields or [])
        if (self.pk  # existing object
            and self.is_live  # object is currently live
            and 'is_live' not in dirty_fields  # but has not just been switched live
            # and fields have been modified that should be static
            and forbidden_changed_fields):
            raise ValueError(
                "Some fields of this object cannot be changed after creation."
                "These fields had disallowed changes:  %s" % forbidden_changed_fields)
        super(ProviderBackedModel, self).save(*args, **kwargs)


class MultiProviderBackedModel(ProviderBackedModel):
    class Meta:
        abstract = True

    def create_provider_versions(self, *args):
        raise NotImplementedError

    def activate(self):
        self.is_active = True
        # The first time the object is activated we take it live on stripe and paypal
        # creating all the necessary objects.
        if not self.is_live:
            self.is_live = True  # A one way state change to show this plan is now live
            self.create_provider_versions()
            logger.info(
                "%s %s has gone live successfully." % (self._meta.verbose_name.title(), self.pk))

        self._call_all_providers_action('activate')
        logger.info("%s %s has been activated successfully." % (
            self._meta.verbose_name.title(), self.pk))
        self.save()

    def deactivate(self):
        self.is_active = False
        self._call_all_providers_action('deactivate')
        logger.info("%s %s has been deactivated successfully." % (
            self._meta.verbose_name.title(), self.pk))
        self.save()

    def delete(self, using=None):
        self._call_all_providers_action('delete')
        super(MultiProviderBackedModel, self).delete(using=using)


class BillingAccount(IcmoModel):
    """ 
        Keeps track of relationships between users, subscriptions, companies,
        etc. An account has one owner and potentially many companies. This
        is distinct from other users having permissions to company data. This
        model deals with account ownership.
    """

    class Meta:
        ordering = ('created',)

    account_number = models.CharField(max_length=11, editable=False, unique=True)
    owner = models.OneToOneField('icmo_users.IcmoUser')

    # null so we can create the object at signup (before the company has been created)
    billing_company = models.ForeignKey('companies.Company', blank=True, null=True)
    active_subscription = models.ForeignKey('Subscription', related_name='active_for_account',
                                            blank=True, null=True)
    limit_max_companies = models.PositiveSmallIntegerField(default=0, blank=True, null=True)

    def set_active_subscription(self, subscription):
        self.active_subscription = subscription
        self.limit_max_companies = subscription.plan.limit_max_companies
        self.save()

    def clear_active_subscription(self, unpublish_companies=True):
        self.active_subscription = None
        self.limit_max_companies = 0
        self.save()

    @staticmethod
    def generate_unique_account_number():
        while True:
            number = "".join([str(randint(0, 9)) for x in range(0, 9)])
            number = re.sub(r'([0-9]{3})(?!$)', '\\1-', number)
            if not BillingAccount.objects.filter(account_number=number).exists():
                return number

    def __unicode__(self):
        return "Account #%s" % self.account_number

    @property
    def slug(self):
        return self.account_number

    def save(self, *args, **kwargs):
        if not self.account_number:
            self.account_number = BillingAccount.generate_unique_account_number()
        return super(BillingAccount, self).save(*args, **kwargs)


class Subscription(ProviderBackedModel):
    account = models.ForeignKey('BillingAccount', editable=False)
    plan = models.ForeignKey('SubscriptionPlan', editable=False)
    coupon = models.ForeignKey('Coupon', editable=False, null=True, blank=True)
    provider_name = models.CharField(max_length=30, blank=True,
                                     choices=SUBSCRIPTION_CHOICES, editable=False)
    status = models.CharField(max_length=255, blank=True, choices=SUBSCRIPTION_STATUS_CHOICES)

    cancel_at_period_end = models.BooleanField(default=False)
    canceled_at = models.DateTimeField(null=True, blank=True, editable=False)
    trial_end = models.DateTimeField(null=True, blank=True)

    @property
    def subscription_fee_terms(self):
        if self.coupon:
            return self.coupon.get_applied_recurring_discount_description(self.plan.amount)
        return "$%s %s" % (self.plan.display_price, self.plan.human_interval)

    @property
    def setup_fee_terms(self):
        if self.coupon:
            return self.coupon.get_applied_setup_fee_discount_description(self.plan.amount)
        return "$%s" % self.plan.setup_fee_amount

    @property
    def subscription_fee_coupon_applied(self):
        if self.coupon and self.coupon.has_pricetype_discount('recurring'):
            return True
        return False

    @property
    def setup_fee_coupon_applied(self):
        if self.coupon.has_pricetype_discount('setup_fee'):
            return True
        return False

    @property
    def provider_plan_id(self):
        if self.provider == PAYMENT_PROVIDER_PAYPAL:
            return self.plan.paypal_plan_id
        elif self.provider == PAYMENT_PROVIDER_STRIPE:
            return self.plan.stripe_plan_id
        raise ValueError("Provider is not configured.")

    def subscribe(self, token, coupon=None):
        """
        Begins the subscription with the payment provider, billing any due amounts.
        :param token: The payment token (stripe card token or paypal postauth token)
        :rtype : string: the new subscription id
        """
        icmo_coupon_id = getattr(coupon, 'id', None)
        self._call_provider_action(
            check_provider(self.provider_name), 'create',
            self.plan_id, self.account.owner.email,
            self.account.owner.get_full_name(),
            token, icmo_coupon_id=icmo_coupon_id
        )
        self.is_active = True
        self.is_live = True
        self.save()
        return True

    def cancel(self, at_period_end=True, note="Canceling the subscription."):
        self._call_provider_action(
            check_provider(self.provider_name), 'cancel', at_period_end=at_period_end, note=note
        )
        self.status = 'canceled'
        self.ended_at = timezone.now()
        logger.info(
            "Subscription for account %s (owner %s) has been canceled." % (
                self.account.account_number, self.account.owner.email
            )
        )
        # fixme implement at_period_end handling
        self.save()

    @property
    def active_contract(self):
        return self.billingcontract_set.all().order_by('-date').first()

    @staticmethod
    def start_subscription(account, plan, provider_name, token, coupon=None):
        """
        Starts the subscription with the payment provider and records all ids.

icmo/apps/billing/providers/stripe/models.py
from django.db import models

from billing.helpers import apply_to_price


class StripeSubscriptionPlanRegistry(models.Model):
    icmo_plan = models.ForeignKey('billing.SubscriptionPlan')
    stripe_plan_id = models.CharField(max_length=255)

    # These aren't captureable in stripe so we record them here separately
    setup_fee_name = models.CharField(max_length=100, blank=True)
    setup_fee_amount = models.PositiveIntegerField(default=0)


class StripeSubscriptionRegistry(models.Model):
    icmo_subscription = models.ForeignKey('billing.Subscription')
    stripe_subscription_id = models.CharField(max_length=255)
    stripe_customer_id = models.CharField(max_length=255)
    card_last_4 = models.CharField(max_length=4, blank=True)
    card_kind = models.CharField(max_length=50, blank=True)
    card_exp_month = models.PositiveIntegerField(blank=True, null=True)
    card_exp_year = models.PositiveIntegerField(blank=True, null=True)


class StripeCouponRegistry(models.Model):
    """
    ICMO coupons affecting both setup fee and recurring fee must be split into two stripe coupons
    This model tracks them.
    """
    icmo_coupon = models.ForeignKey('billing.Coupon')
    stripe_coupon_id = models.CharField(max_length=255, blank=True)

    # These aren't captureable in stripe so we record them here separately
    setup_fee_amount_off = models.DecimalField(max_digits=7, decimal_places=2, blank=True,
                                               null=True)
    setup_fee_percent_off = models.PositiveIntegerField(blank=True, null=True)

    def get_discounted_setup_fee(self, setup_fee_amount):
        if self.setup_fee_amount_off:
            return int(apply_to_price('amount_off', self.setup_fee_amount_off, setup_fee_amount))
        elif self.setup_fee_percent_off:
            return int(apply_to_price('percent_off', self.setup_fee_percent_off, setup_fee_amount))
        return setup_fee_amount

icmo/apps/dashboards/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from core.models import IcmoModel


class Dashboard(IcmoModel):
    class Meta:
        unique_together = ('company', 'slug')
    slug = AutoSlugField(populate_from=('company', 'name'))
    company = models.ForeignKey('companies.Company', blank=True, null=True)
    user = models.ForeignKey('icmo_users.IcmoUser', blank=True, null=True)
    name = models.CharField(max_length=255)

icmo/apps/pardot/models.py
from django.db import models

# Create your models here.

icmo/apps/reports/models.py
from django.db import models

# Create your models here.

icmo/templates/accounts/account.html
{% extends 'base_main.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block title %}Account Settings{% endblock %}
{% block page_title %}Account Settings{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">User Profile
                        <a role="button" href="?edit=user" class="pull-right btn btn-primary">
                            <i class="fa fa-pencil-square-o"></i>
                        </a>
                    </h3>
                </div>
                <div class="box-body">
                    {% if user_form %}
                        {% crispy user_form %}
                    {% else %}
                        <p><b>Name</b><br>{{ user.get_full_name }}</p>
                        <p><b>Email</b><br>{{ user.email }}</p>
                        <p><b>Password</b><br><a href="{% url 'password_change' %}">Change your
                            password</a></p>
                        <p><b>Phone Number</b><br>{{ user.phone_number }}</p>
                        <p><b>Title</b><br>{{ user.title }}</p>
                        <p><b>Employer</b><br>{{ user.employer }}</p>
                        <p><b>Timezone</b><br>{{ user.timezone }}</p>
                        <p><b>Date Joined</b><br>{{ user.date_joined }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if billing %}
            <div class="col-sm-6">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Billing Account
                            <a role="button" href="#"
                               onclick='bootbox.alert("To modify your subscription please contact us at 1-800-735-6520");'
                               class="pull-right btn btn-primary btn-bordered">
                                Change Subscription
                            </a>
                        </h3>
                    </div>
                    <div class="box-body">
                        <p><b>Account Number</b><br>{{ billing.account_number }}</p>

                        <p><b>Owner</b><br>{{ billing.owner }}</p>

                        <p><b>Billing Company</b><br>{{ billing.billing_company }}</p>

                        <p><b>Active Subscription</b><br>{{ billing.active_subscription }}</p>

                        <p><b>Max Number of Published
                            Companies</b><br>{{ billing.limit_max_companies }}</p>

                        <p><b>Current Contract</b><br>
                            {% if billing.active_subscription %}
                                {% with contract=billing.active_subscription.active_contract %}
                                    <a href="{% url 'billing:contract_view' slug=contract.slug %}?pdf=1"
                                       target="_blank">
                                        <i class="fa fa-file-pdf-o"></i> Billing Contract
                                        v{{ contract.version }} {{ contract.date }} PDF
                                    </a>
                                {% endwith %}
                                </p>
                            {% endif %}
                        </p>
                        <p><b>Other Contracts</b><br>
                            {% for contract in billing.contract_set.all %}
                                <a href="{% url 'billing:contract_view' slug=contract.slug %}?pdf=1"
                                   target="_blank">
                                    <i class="fa fa-file-pdf-o"></i> Billing Contract
                                    v{{ contract.version }} {{ contract.date }} PDF
                                </a>
                                </p>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

icmo/templates/accounts/integrations.html
{% extends 'base_main.html' %}
{% load crispy_forms_tags static %}
{% load blank_kwargs_url from icmo_utils %}

{% block title %}Integrations{% endblock %}
{% block page_title %}Integrations{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Available Integrations</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <a href="{% blank_kwargs_url 'hubspot_setup' %}"
                               title="HubSpot">
                                <img height=75  src="{% static 'img/integrations/hubspot.png' %}"
                                     class="img">
                            </a>
                        </div>
                        <div class="col-md-3">
                            <a href="{% blank_kwargs_url 'sfdc_manage' %}">
                                <img height=75 src="{% static 'img/integrations/salesforce.png' %}"
                                     class="img">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

icmo/templates/accounts/recycle_bin.html
{% extends 'base_main.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% load blank_kwargs_url from icmo_utils %}

{% load i18n %}

{% block title %}Recycle Bin{% endblock %}
{% block page_title %}Recycle Bin{% endblock %}
{% block page_js %}
    {{ block.super }}
    <script type="text/javascript">
        function processAction($btn) {
            $.post({
                url: "{% blank_kwargs_url 'recycle_bin' %}",
                data: {
                    action: $btn.data('action'),
                    uniqueSlug: $btn.data('unique-slug'),
                    objectType: $btn.data('object-type')
                }

            }).always(function(){
                location.reload();
            });
        }
        $(function () {
            var $el = $('#recycleBinGrid');
            $el.find('button').click(function (e) {
                var $btn = $(e.target).closest('button'),
                        action = $btn.data('action');
                if (action == 'restore') {
                    processAction($btn);
                } else if (action == 'delete') {
                    bootbox.confirm(
                            "This will permanently delete this item AND all items nested underneath it, are you sure you want to proceed?",
                            function () {
                                processAction($btn);
                            }
                    )
                }
            });
        });
    </script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Items in the Recycle Bin</h3>
                </div>
                <div class="box-body">
                    <table width="100%" id="recycleBinGrid">
                        <tr>
                            <th>Object Type</th>
                            <th>Name</th>
                            <th>Discarded On</th>
                            <th>Discarded By</th>
                            <th>Actions</th>
                        </tr>
                        {% for item in inactive_items %}
                            <tr>
                                <td>{{ item.type }}</td>
                                <td>{{ item.name }}</td>
                                <td>{{ item.deactivated }}</td>
                                <td>{{ item.deactivated_by.get_full_name }}</td>
                                <td>
                                    <button class="btn btn-primary"
                                            title="Restore"
                                            data-action="restore"
                                            data-unique-slug="{{ item.unique_slug }}"
                                            data-object-type="{{ item.type }}">
                                        <i class="fa fa-undo"></i>
                                    </button>
                                    <button class="btn btn-danger"
                                            title="DELETE PERMANENTLY"
                                            data-action="delete"
                                            data-unique-slug="{{ item.unique_slug }}"
                                            data-object-type="{{ item.type }}">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="box-footer">Anything you delete in intelligentRevenue will appear here and
                    can be restored by clicking the restore button.
                </div>
            </div>
        </div>
    </div>
{% endblock %}

icmo/templates/accounts/send_a_suggestion.html
{% extends 'base_main.html' %}
{% load crispy_forms_tags %}
{% load blank_kwargs_url from icmo_utils %}

{% block title %}Send a Suggestion{% endblock %}
{% block page_title %}Send a Suggestion{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">How can we improve?</h3>
                    <br><br><p>We are committed to providing the tools
                        you need to succeed.  If there something we should know, please
                    <a href="{% blank_kwargs_url  'help' %}">get in touch with our support team</a>, or for less urgent requests leave
                    us a suggestion using the form below.</p>
                </div>
                <div class="box-body">

                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}